In [1]:
from tensorflow.keras.datasets import mnist

I0000 00:00:1774347613.454467   46056 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1774347613.896432   46056 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1774347617.178221   46056 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.


In [16]:
import numpy as np

In [2]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [4]:
train_images.shape


(60000, 28, 28)

In [5]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], shape=(60000,), dtype=uint8)

In [7]:
test_images.shape

(10000, 28, 28)

In [8]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], shape=(10000,), dtype=uint8)

In [9]:
from tensorflow import keras
from tensorflow.keras import layers


In [ ]:
model = keras.Sequential([
layers.Dense(512, activation="relu"),
layers.Dense(10, activation="softmax")
])

# second (and last) layer is a 10-way
# softmax classification layer, which means it will return an array of 10 probability scores
# (summing to 1). Each score will be the probability that the current digit image
# belongs to one of our 10 digit classes.

To make the model ready for training, we need to pick three more things as part of the compilation step:

- **An optimizer** — The mechanism through which the model will update itself based on the training data it sees, so as to improve its performance.
- **A loss function** — How the model will be able to measure its performance on the training data, and thus how it will be able to steer itself in the right direction.
- **Metrics to monitor during training and testing** — Here, we’ll only care about accu-
racy (the fraction of the images that were correctly classified).

In [11]:
model.compile(optimizer="rmsprop",
loss="sparse_categorical_crossentropy",
metrics=["accuracy"])

E0000 00:00:1774348573.929131   46056 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [ ]:
#Before training, we’ll preprocess the data by reshaping it into the shape the model
#expects and scaling it so that all values are in the [0, 1] interval. Previously, our train-
#ing images were stored in an array of shape (60000, 28, 28) of type uint8 with values
#in the [0, 255] interval. We’ll transform it into a float32 array of shape (60000, 28 *
#28) with values between 0 and 1.

In [14]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [15]:
train_images.shape

(60000, 784)

In [ ]:

# 60000 observações
# 5 épocas = 5 passagens completas sobre todo o conjunto de treino
# cada época tem 469 steps (batches):
#   - 468 batches de 128 observações
#   - 1 batch final de 96 observações

In [19]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5


W0000 00:00:1774355049.796281   46056 cpu_allocator_impl.cc:82] Allocation of 188160000 exceeds 10% of free system memory.


469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9243 - loss: 0.2637
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.9686 - loss: 0.1072
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9790 - loss: 0.0708
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9850 - loss: 0.0506
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9888 - loss: 0.0384


In [20]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step


In [22]:
predictions[0]

array([2.1723848e-08, 3.5610019e-09, 4.6462301e-05, 3.4613306e-05,
       3.1699355e-12, 1.6338204e-08, 4.2180880e-13, 9.9991828e-01,
       2.0584808e-07, 4.4735356e-07], dtype=float32)

In [23]:
# Each number of index i in that array corresponds to the probability that digit image
# test_digits[0] belongs to class i.

In [24]:
predictions[0].argmax()

np.int64(7)

In [25]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9785 - loss: 0.0663


In [26]:
print(f"test_acc: {test_acc}")

test_acc: 0.9785000085830688
